### ISSUE TITLE
Improve documentation and examples

### ISSUE THREAD

**Issue by hielsnoppe** [fraunhoferfokus/Fuzzino#1]
Examples on how to get started using the Java API would be particularly helpful.

**Comment by martin-schneider** [comment]
Please have a look hereat /doc/examples/Java

**Comment by hielsnoppe** [comment]
Thanks for the reply! I was looking for more extensive documentation, though. I forked the project and started a [wiki](https://github.com/hielsnoppe/Fuzzino/wiki). Feel free to copy whatever you see fit. I also plan to send a pull request as soon as I have created more examples.
